import os

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if GROQ_API_KEY:
    os.environ["GROQ_API_KEY"] = GROQ_API_KEY

COHERE_API_KEY = os.getenv("COHERE_API_KEY")
if COHERE_API_KEY:
    os.environ["COHERE_API_KEY"] = COHERE_API_KEY

LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")
if LANGCHAIN_API_KEY:
    os.environ["LANGCHAIN_API_KEY"] = LANGCHAIN_API_KEY

LANGCHAIN_TRACING_V2 = os.getenv("LANGCHAIN_TRACING_V2")
if LANGCHAIN_TRACING_V2:
    os.environ["LANGCHAIN_TRACING_V2"] = LANGCHAIN_TRACING_V2
