tables:
  - name: customers
    description: Stores customer information including name, credit limits, contact and address details.

  - name: employees
    description: Stores information about company employees, including reporting hierarchy.

  - name: offices
    description: Stores office location and contact details.

  - name: orders
    description: Contains customer orders including order status and dates.

  - name: orderdetails
    description: Stores the details of each order including products and quantities.

  - name: payments
    description: Records customer payments, including payment date and amount.

  - name: products
    description: Stores product data such as name, scale, vendor, and pricing.

  - name: productlines
    description: Stores product line categories and associated text descriptions.
