math_search:
  transport: stdio
  command: python
  args:
    - servers/math_search.py

weather_search:
  transport: streamable_http
  url: http://localhost:8000/mcp

sql_search:
  transport: streamable_http
  url: http://localhost:8001/mcp

vector_search:
  transport: streamable_http
  url: http://localhost:8002/mcp